chore: organize repository, add NVIDIA guide
defenseunicorns/leapfrogai-deployment pull request #12
Opened 2024-01-24 20:23 UTC by justinthelaw

2024-01-24 21:15 UTC, CollectiveUnicorn requested changes

2024-01-24 21:15 UTC, CollectiveUnicorn commented on README.md
> +## Future Improvements
Lets turn these into issues and remove this section

2024-01-24 21:15 UTC, CollectiveUnicorn commented on INSTALL-CPU.md
> +# perform the following key presses and actions:
Should probably just do the kyverno config with kubectl and put the kubectl command in here

2024-01-24 21:15 UTC, CollectiveUnicorn commented on INSTALL-NVIDIA.md
> +> The GPU and CPU-only installation are very similar, so if you are installing with GPU support, bring the INSTALL-CPU.md as well, since all the instructions in this markdown only point out the steps
While I get not want to duplicate things, this requires that people go back and forth between two readme's to figure out what to do. Can we just copy over the instructions for the time being?

2024-01-24 21:15 UTC, CollectiveUnicorn commented
What do you think about keeping the readme in one doc while just using drop downs, one for cpu and one for gpu like this: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections

2024-01-25 22:58 UTC, CollectiveUnicorn commented
We also need to put llama-cpp instructions in there because atm there's only ctransformers

2024-01-25 23:02 UTC, justinthelaw commented
These new instructions only include Llama-cpp. CTransformers was already removed.

2024-01-26 00:28 UTC, gerred commented
As I finish up some of the UDS bundle work and UDS core work, do you want me to include the updated instructions in this PR or have that as a separate PR? I'm thinking rn it'll be mostly command changes and some removals, but if I can knock this out by tomorrow would love to get the updated instructions in ASAP.

2024-01-26 01:36 UTC, justinthelaw commented
@gerred There are still some fixes I want to make on this based on Gato's feedback and for the sake of organization/prettiness.

If you pull down this branch and add a README with what you've done differently, I can merge it into the markdowns that I already have, and then test to see if I'm also able to deploy using UDS core.

2024-01-29 19:54 UTC, CollectiveUnicorn submitted a review, later dismissed

2024-01-30 17:03 UTC, CollectiveUnicorn approved these changes

2024-01-30 17:25 UTC, merged